### ISSUE TITLE
Aquatic Mine Water Surface Transparency

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#15]
I noticed that the way the surface of the water for Aquatic Mine is done in the Dreamcast version has it so that only the area immediately around Knuckles is transparent instead of the full surface, making it look more murky than other instances of water in the game.
![AquaticMineWaterTransparency](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/1d42a572-f340-4c14-b1a3-3608ec586425)
![AQwaterbattle](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/dd046902-6253-4764-b113-e7c64f905374)

**Comment by shaddatic** [comment]
With a little bit of model knowhow, got this one back up and working! Turns out it wasn't missing at all, but the water was already too transparent for the effect to be super visible.

No further discussion needed, closing as complete.

![213610_20230629212134_1](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/f0a57c1c-9739-4b59-84d6-3ddc6c0c96de)
