### ISSUE TITLE
Misaligned light on street lights

### ISSUE THREAD

**Issue by Lg1955** [shaddatic/sa2b-render-fix#29]
The light on Street lights are misaligned on PC, while they arent on Dreamcast
The issue also existed in the Gamecube version   

Dreamcast
![Screenshot (43)](https://github.com/shaddatic/sa2b-render-fix/assets/40836768/5ec07c66-d470-4ab7-bf9d-5a79662cd6bb)
![Screenshot 2023-07-02 013315](https://github.com/shaddatic/sa2b-render-fix/assets/40836768/d039ae5e-2a44-417a-9b07-d684584d347a)

PC
![Screenshot (39)](https://github.com/shaddatic/sa2b-render-fix/assets/40836768/7720f0f2-78a8-4071-a5c7-fad7fc558a9e)
![Screenshot (45)](https://github.com/shaddatic/sa2b-render-fix/assets/40836768/55216599-b32f-4322-8c5e-a0b7eba0f341)

GameCube
![Screenshot (47)](https://github.com/shaddatic/sa2b-render-fix/assets/40836768/5687cfc8-1000-4e7b-b103-c19e4ce86457)
![Screenshot (46)](https://github.com/shaddatic/sa2b-render-fix/assets/40836768/d1efc620-0ed4-4100-a287-c95cd7329731)

**Comment by Sonikko** [comment]
I would add to this that the lights on the cars are misaligned too, and some are too transparent or missing altogether (maybe because they render inside the car model?).
DC
![MS1 lights DC](https://github.com/shaddatic/sa2b-render-fix/assets/24740235/03abedde-32ca-468f-821e-008021a28316)
![MS2 lights DC](https://github.com/shaddatic/sa2b-render-fix/assets/24740235/0dfdac0c-b091-4a83-9500-0c72d94591e6)

PC
![photo_2023-07-05_13-24-20](https://github.com/shaddatic/sa2b-render-fix/assets/24740235/acb4fa55-e75e-43d2-b8ec-018ef5354e0d)
![photo_2023-07-05_13-22-04](https://github.com/shaddatic/sa2b-render-fix/assets/24740235/b3369d5f-5dd5-4e00-b1f8-8c80db1e808e)

The headlights seem to be there in the first pictures on the car closest to the camera, but they're very faint and misaligned, they're completely missing on the other car.
Same in the second picture. The cherry lights are misaligned on all cars.

**Comment by shaddatic** [comment]
Finally tracked this one down.
![image](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/5991ca74-c40d-4ddc-8b35-6948a3f2d148)
I'll get this fix merged once I'm happy with it, and finally get it behind me haha
