### ISSUE TITLE
Plane shadows Metal Harbor

### ISSUE THREAD

**Issue by Sonikko** [shaddatic/sa2b-render-fix#39]
Shadows for the planes appear to be downgraded from Dreamcast, they appear circular on PC, are completely missing on GC.

DC
![dc shadow plane](https://github.com/shaddatic/sa2b-render-fix/assets/24740235/ffad5655-f024-4cee-9e68-c4255948ca40)

PC
![pc shadow plane](https://github.com/shaddatic/sa2b-render-fix/assets/24740235/b9ee5cf4-ffea-467c-a8ea-83f92a0c75e0)

**Comment by shaddatic** [comment]
The circlular shadows are intentional and are a feature of this mod called 'Restore Extra Shadows.' There are no plans to restore the Dreamcast shadows as this is not a Dreamcast restoration mod, and there's a mod that already does that.

Closing as out-of-scope/working-as-intended. Thanks for the report

**Comment by shaddatic** [comment]
This issue is no longer out of scope

**Comment by shaddatic** [comment]
But it's also completed
