### ISSUE TITLE
Particle effect missing on GUN robots

### ISSUE THREAD

**Issue by Sonikko** [shaddatic/sa2b-render-fix#41]
The purple glow particle effect is missing on the robots, it's present on the EGG Beetles though

DC
![DC Particle](https://github.com/shaddatic/sa2b-render-fix/assets/24740235/f7024f2e-13d6-4e88-96d2-0557f840c7e7)

PC
![PC Particle](https://github.com/shaddatic/sa2b-render-fix/assets/24740235/7450d568-332b-4135-993c-7a6ff888fbd3)

**Comment by Ellasent** [comment]
I'm sorry to butt in, but this is probably due to the fact you're using the DC GUN Hunter mod. I can tell because of their skinnier legs. But yeah, I've had this problem when I had that mod activated, and I decided it'd just be better to stick with the Battle GUN Hunters to keep that light instead of sacrificing it for the sake of consistency with the inactive GUN Hunters in Weapons Bed.
I hope this helps.

**Comment by Sonikko** [comment]
Can confirm it was the mod, guess this would be part of an eventual all-in-one Dreamcast Conversion then
