### ISSUE TITLE
Rouge Cannon's Core Pit

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#6]
This was an issue I remember finding out about a while back, where the pit that the all of cooling liquid in Rouge's section of Cannon's Core drains into just suddenly ends in Battle, where as in the Dreamcast version where it's more of an actual pit and all that.
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/38a181a6-d1af-48e9-b141-2086010c0379)
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/19f03cc0-6943-47f2-9b58-306e94e0dd03)
I don't know how much this fits under Render Fixes since it just seems like a really weird thing that was done to the stage geometry, but I figure it's still at least worth mentioning.

**Comment by shaddatic** [comment]
I've added the possibly-intentional tag because I could see them making this change if players kept getting confused. On the other hand, the Battle port was in development before the Dreamcast version was complete, so this could be an actual issue.

It will be looked at when I've got time.

**Comment by shaddatic** [comment]
Can't believe I had to do that, but yes this is an intentional change for some reason. I can tell because the area has very specific geometry and vertex color changes that can't happen on accident. 

Haven't had a chance to try out my restoration of the original model yet, but as far as I can tell the original pit is still there and was just modeled over. So by removing that geometry and restoring the original vertex colors, this should look normal again.

**Comment by shaddatic** [comment]
Apparently, importing Ginja models into Blender with the addon is broken atm. That's okay, I was able to use the land model from the Dreamcast version. With very few alterations to materials, it's restored to back to how it used to look.

It will be included in the next update, closing this issue as complete.

![213610_20230629001437_1](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/104f1e5a-d9db-43a3-97ab-47da7d7b0718)
