### ISSUE TITLE
Prison Lane: Search Light Transparency Issues

### ISSUE THREAD

**Issue by NikkMann** [shaddatic/sa2b-render-fix#62]
On PC the icons for power-ups render above everything, on DC they do not.

PC (the +10 rings rendering on top of the yellow spotlight in the upper right)
![sonic2app 2023-10-23 14-50-08](https://github.com/shaddatic/sa2b-render-fix/assets/90150509/fa34b943-ecf7-46dc-9a4b-2b4a353ac9ff)

DC (same object, properly rendered behind the spotlight)
![image](https://github.com/shaddatic/sa2b-render-fix/assets/90150509/dc7d1635-4d21-4c58-84ec-b4fba04befdf)

**Comment by shaddatic** [comment]
Switching the search lights to the sorted display layer fixed the particular issue shown in the images. Since this issue is a little broad and the issue shown is an issue with the search lights drawing too early, not the itemboxes, I'm considering it closed

![image](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/3aa3a3b1-47a4-4f92-9a59-44c59b5cbaae)
